version: '3.5'

secrets:
  db_password:
    file: ./pass.txt
  discord_api_key:
    file: ./discord_api_key.txt

services:
  discord_bot_postgres:
    container_name: discord_bot_postgres
    image: postgres:11.6
    command: 
      ls /run/secrets
    secrets:
      - discord_api_key
      - db_password
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "{{ HERE YOUR PAPERTRAIL LOG DESTINATION }}"
    #     tag: "{{.Name}}/{{.ID}}"
    environment:
      POSTGRES_USER: discord
      POSTGRES_PASSWORD: /run/secrets/db_password
      PGDATA: /data/postgres
    volumes:
      - ./volumes/postgres:/data/postgres
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    expose:
      - "5435"
    restart: unless-stopped

  discord_bot:
    container_name: discord_bot
    # image: discord_bot:1
    build: ./../
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "{{ HERE YOUR PAPERTRAIL LOG DESTINATION }}"
    #     tag: "{{.Name}}/{{.ID}}"
    depends_on:
      - discord_bot_postgres
    environment:
      DISCORD_APIKEY: /run/secrets/discord_api_key
      LOG_LEVEL: info
      CONNECTORS_CHOLLOMETRO_ENABLED: "true"
      CONNECTORS_CHOLLOMETRO_TIMEOUT: 900000
      PGHOST: discord_bot_postgres
      PGPASSWORD: /run/secrets/db_password
      PGUSER: discord
      PGDATABASE: connectors
      PGPORT: 5432
    secrets:
      - discord_api_key
      - db_password
    restart: always