version: '3.5'
services:
  discord_bot_postgres:
    container_name: discord_bot_postgres
    image: postgres:11.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /data/postgres
    secrets:
      - db_password
      - discord_api_key
    volumes:
      - ./volumes/postgres:/data/postgres
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5434:5432'
    restart: unless-stopped

  discord_bot:
    container_name: discord_bot
    # image: discord_bot:1
    build: ./../
    depends_on:
      - discord_bot_postgres
    environment:
      DISCORD_APIKEY_FILE: /run/secrets/discord_api_key
      LOG_LEVEL: info
      CONNECTORS_CHOLLOMETRO_ENABLED: 'true'
      CONNECTORS_CHOLLOMETRO_TIMEOUT: 900000
      PGHOST: discord_bot_postgres
      PGPASSWORD_FILE: /run/secrets/db_password
      PGUSER: postgres
      PGDATABASE: connectors
      PGPORT: 5432
    secrets:
      - db_password
      - discord_api_key
    restart: always

secrets:
  db_password:
    file: pass.txt
  discord_api_key:
    file: discord_api_key.txt
